[colors.primary]
background = "#00171d"
foreground = "#fdf6e3"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 10.0

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[[mouse.bindings]]
action = "Copy"
mouse = "Right"

[window]
dynamic_title = true
opacity = 0.9

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 237
lines = 72
